name: revup_core
description: Core package for revup app
version: 6.3.11-dev+1

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^4.0.0
  cloud_firestore: ^3.4.6
  cloud_functions: ^3.3.5
  connectivity_plus: ^2.3.6
  dartz: ^0.10.1
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  firebase_storage: ^10.3.7
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  google_sign_in: ^5.3.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.0.0-dev.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  momo_vn:
    git:
      url: https://github.com/minhvn/momo.vn.git
      ref: master
      version: ^2.0.2
  path_provider: ^2.0.11

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  dart_code_metrics: ^4.17.1
  dependency_validator: ^3.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

import_sorter:
  comments: false
